[metadata]
name = na6plist
version = 0.1.0
description = NA60plus build CLI
long_description = file: README.md
long_description_content_type = text/markdown
author = NA60plus

[options]
packages = na6plist
package_dir =
    na6plist = .
include_package_data = True
install_requires =

[options.package_data]
na6plist =
    recipes/*.sh

[options.entry_points]
console_scripts =
    na6pbuild = na6plist.cli:main

[tool:pytest]
python_files = tests.py test_*.py *_tests.py
